services:
  app:
    build: .
    container_name: gs-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
    mem_limit: 512m
    cpus: "0.50"
    networks:
      - gs-net

networks:
  gs-net: