services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start --proxy=edge --hostname=${KC_HOSTNAME}
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KC_HEALTH_ENABLED: "true"

      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m -XX:+ExitOnOutOfMemoryError"

      KC_DB_POOL_MIN_SIZE: "5"
      KC_DB_POOL_MAX_SIZE: "10"
    mem_limit: 768m
    cpus: "0.50"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10

    restart: unless-stopped
