services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start --proxy=edge --hostname=${KC_HOSTNAME}
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "127.0.0.1:8082:8080"
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
volumes:
  keycloak_data:
